all: NameNode.class DataNode.class Client.class HdfsDefn.class

NameNode.class: src/ds/hdfs/NameNode.java
	javac -cp src/project2-0.0.1-SNAPSHOT-jar-with-dependencies.jar src/ds/hdfs/NameNode.java

DataNode.class: src/ds/hdfs/DataNode.java
	javac -cp src/project2-0.0.1-SNAPSHOT-jar-with-dependencies.jar src/ds/hdfs/DataNode.java

Client.class: src/ds/hdfs/Client.java
	javac -cp src/project2-0.0.1-SNAPSHOT-jar-with-dependencies.jar src/ds/hdfs/Client.java

HdfsDefn.class: src/ds/hdfs/HdfsDefn.java
	javac -cp src/project2-0.0.1-SNAPSHOT-jar-with-dependencies.jar src/ds/hdfs/HdfsDefn.java
